import type { Metadata } from "next";
import "./globals.scss";
import { Header } from "@/components/Header/Header";
import { CartProvider } from "@/context/ProductContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
        <body>
          <Header />
          {children}
        </body>
      </CartProvider>
    </html>
  );
}
